// examples/svelte-app/src/dashboards/FlightsDashboard.svelte
<!-- src/lib/dashboards/FlightsDashboard.svelte -->
<!-- This Svelte component replicates the FlightsDashboard from the React app. -->
<script lang="ts">
  import { onMount } from 'svelte';
  import * as vg from '@uwdata/vgplot';
  import {
    useMosaicSelection,
    DataTable,
  } from '@nozzle/mosaic-tanstack-svelte-table';
  import { vgplot } from '../utils/vgplot';
  import { flightsLogicConfig, flightsUIConfig } from '../tables';
  let dashboardElement: HTMLElement | null = null;
  let isReady = false;
  let setupRan = false;

  const querySel = useMosaicSelection('flights_query');
  const brushSel = useMosaicSelection('flights_brush');
  const rowSelectionSel = useMosaicSelection('flights_rowSelection');
  const internalFilterSel = useMosaicSelection('flights_internal_filter');

  onMount(async () => {
    if (setupRan) return;
    setupRan = true;

    const fileURL =
      'https://pub-1da360b43ceb401c809f68ca37c7f8a4.r2.dev/data/flights-10m.parquet';
    const dataSetupQuery = `
      CREATE OR REPLACE TABLE flights_10m AS 
      SELECT ROW_NUMBER() OVER () AS id,
        GREATEST(-60, LEAST(ARR_DELAY, 180))::DOUBLE AS delay, 
        DISTANCE AS distance, DEP_TIME AS time 
      FROM '${fileURL}'`;
    await vg.coordinator().exec(dataSetupQuery);

    // --- FIX: Build the plot programmatically, removing the spec parser dependency ---
    dashboardElement = vg.vconcat(
      vg.plot(
        vg.rectY(vg.from('flights_10m', { filterBy: querySel }), {
          x: vg.bin('delay'),
          y: vg.count(),
          fill: 'steelblue',
          insetLeft: 0.5,
          insetRight: 0.5,
        }),
        vg.intervalX({ as: brushSel }),
        vg.xDomain(vg.Fixed),
        vg.xLabel('Arrival Delay (min) →'),
        vg.yTickFormat('s'),
        vg.width(600),
        vg.height(200),
      ),
      vg.plot(
        vg.rectY(vg.from('flights_10m', { filterBy: querySel }), {
          x: vg.bin('time'),
          y: vg.count(),
          fill: 'steelblue',
          insetLeft: 0.5,
          insetRight: 0.5,
        }),
        vg.intervalX({ as: brushSel }),
        vg.xDomain(vg.Fixed),
        vg.xLabel('Departure Time (hour) →'),
        vg.yTickFormat('s'),
        vg.width(600),
        vg.height(200),
      ),
      vg.plot(
        vg.rectY(vg.from('flights_10m', { filterBy: querySel }), {
          x: vg.bin('distance'),
          y: vg.count(),
          fill: 'steelblue',
          insetLeft: 0.5,
          insetRight: 0.5,
        }),
        vg.intervalX({ as: brushSel }),
        vg.xDomain(vg.Fixed),
        vg.xLabel('Flight Distance (miles) →'),
        vg.yTickFormat('s'),
        vg.width(600),
        vg.height(200),
      ),
    );

    isReady = true;
  });
</script>

<div>
  <h2>10 Million US Flights</h2>
  <p>
    This dashboard shows three histograms of flight data. Brushing on one
    histogram (clicking and dragging) will cross-filter the other two, updating
    their distributions to reflect the selected data subset.
  </p>
  {#if isReady}
    <div use:vgplot={dashboardElement} />
    <div style="margin-top: 1rem;">
      <DataTable
        logicConfig={flightsLogicConfig}
        uiConfig={flightsUIConfig}
        filterBy={querySel}
        rowSelectionAs={rowSelectionSel}
        internalFilterAs={internalFilterSel}
      />
    </div>
  {:else}
    <div>Loading Flights Dashboard...</div>
  {/if}
</div>

// examples/react/app/src/dashboards/FlightsDashboard.tsx
// src/FlightsDashboard.tsx
// UI component for the Flights dashboard, handling one-time data load
// and rendering vgplot visuals alongside the React data table.
import React, { useEffect, useRef, useState } from 'react';
import * as vg from '@uwdata/vgplot';
import { useMosaicSelection } from '@nozzle/mosaic-tanstack-react-table';
import { Vgplot } from '../utils/vgplot';
import { FlightsTable } from '../tables';

export function FlightsDashboard() {
  const [dashboard, setDashboard] = useState<HTMLElement | null>(null);
  const [isReady, setIsReady] = useState(false);
  const setupRan = useRef(false);

  // The query selection no longer includes the internal table filter.
  const querySel = useMosaicSelection('flights_query');
  const brushSel = useMosaicSelection('flights_brush');
  const rowSelectionSel = useMosaicSelection('flights_rowSelection');
  const internalFilterSel = useMosaicSelection('flights_internal_filter');

  useEffect(() => {
    if (setupRan.current) return;
    setupRan.current = true;

    async function setupDashboard() {
      // UPDATED: Use the exact same URL and query as the Svelte version.
      const fileURL =
        'https://pub-1da360b43ceb401c809f68ca37c7f8a4.r2.dev/data/flights-10m.parquet';
      const dataSetupQuery = `
        CREATE OR REPLACE TABLE flights_10m AS 
        SELECT ROW_NUMBER() OVER () AS id,
          GREATEST(-60, LEAST(ARR_DELAY, 180))::DOUBLE AS delay, 
          DISTANCE AS distance, DEP_TIME AS time 
        FROM '${fileURL}'`;
      await vg.coordinator().exec(dataSetupQuery);

      const plotDashboard = vg.vconcat(
        vg.plot(
          vg.rectY(vg.from('flights_10m', { filterBy: querySel }), {
            x: vg.bin('delay'),
            y: vg.count(),
            fill: 'steelblue',
            insetLeft: 0.5,
            insetRight: 0.5,
          }),
          vg.intervalX({ as: brushSel }),
          vg.xDomain(vg.Fixed),
          vg.xLabel('Arrival Delay (min) →'),
          vg.yTickFormat('s'),
          vg.width(600),
          vg.height(200),
        ),
        vg.plot(
          vg.rectY(vg.from('flights_10m', { filterBy: querySel }), {
            x: vg.bin('time'),
            y: vg.count(),
            fill: 'steelblue',
            insetLeft: 0.5,
            insetRight: 0.5,
          }),
          vg.intervalX({ as: brushSel }),
          vg.xDomain(vg.Fixed),
          vg.xLabel('Departure Time (hour) →'),
          vg.yTickFormat('s'),
          vg.width(600),
          vg.height(200),
        ),
        vg.plot(
          vg.rectY(vg.from('flights_10m', { filterBy: querySel }), {
            x: vg.bin('distance'),
            y: vg.count(),
            fill: 'steelblue',
            insetLeft: 0.5,
            insetRight: 0.5,
          }),
          vg.intervalX({ as: brushSel }),
          vg.xDomain(vg.Fixed),
          vg.xLabel('Flight Distance (miles) →'),
          vg.yTickFormat('s'),
          vg.width(600),
          vg.height(200),
        ),
      );

      setDashboard(plotDashboard);
      setIsReady(true);
    }

    setupDashboard();
  }, [querySel, brushSel]);

  return (
    <div>
      <h2>10 Million US Flights</h2>
      <p>
        This dashboard shows three histograms of flight data. Brushing on one
        histogram (clicking and dragging) will cross-filter the other two,
        updating their distributions to reflect the selected data subset.
      </p>
      {isReady ? (
        <>
          <Vgplot plot={dashboard} />
          <div style={{ marginTop: '1rem' }}>
            {/* The table's filterBy prop correctly receives the external filters */}
            <FlightsTable
              filterBy={querySel}
              rowSelectionAs={rowSelectionSel}
              internalFilterAs={internalFilterSel}
            />
          </div>
        </>
      ) : (
        <div>Loading Flights Dashboard...</div>
      )}
    </div>
  );
}
